# Mocha Test Configuration

# Test files pattern
spec: 'test/**/*.test.ts'

# Require ts-node for TypeScript support with transpile-only for speed
require:
  - 'ts-node/register/transpile-only'

# Use experimental loader for ESM support
node-option:
  - 'loader=ts-node/esm'

# Test environment
ui: 'bdd'
reporter: 'spec'

# Timeout settings
timeout: 5000

# Exit after tests complete
exit: true

# Use colors in output
color: true

# Include source maps
full-trace: true