# Mocha Test Configuration

# Use tsx for TypeScript support (handles both TS and JS)
node-option:
    - 'import=tsx'

# Test files pattern - only src/ unit tests by default
spec:
    - 'src/**/*.test.ts'

# Watch files for changes
watch-files:
    - 'src/**/*.ts'

# Timeout settings
timeout: 5000

# Exit after tests complete
exit: true

# Use colors in output
color: true

# Include source maps
full-trace: true
